application: miptracker-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: django
  version: "1.3"

handlers:
- url: /static/
  static_dir: static
  
- url: /.*
  script: main.app
